services:
  hire-smart-backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hiresmart-backend-app:latest
    container_name: hire-smart-backend-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./html/hiresmart-backend.rokanchowdhuryonick.com:/var/www/html
    networks:
      - hire-smart-backend-network
    depends_on:
      - hire-smart-backend-db
      - hire-smart-backend-redis
    environment:
      - DB_HOST=hire-smart-backend-db
      - DB_DATABASE=${DB_DATABASE:-hire_smart}
      - DB_USERNAME=${DB_USERNAME:-hire_smart_user}
      - DB_PASSWORD=${DB_PASSWORD:-hire_smart_password}
      - REDIS_HOST=hire-smart-backend-redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis

  hire-smart-backend-nginx:
    image: nginx:stable
    container_name: hire-smart-backend-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./html/hiresmart-backend.rokanchowdhuryonick.com:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hire-smart-backend-app
    networks:
      - hire-smart-backend-network

  hire-smart-backend-db:
    image: postgres:15
    container_name: hire-smart-backend-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-hire_smart}
      POSTGRES_USER: ${DB_USERNAME:-hire_smart_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-hire_smart_password}
    volumes:
      - hire-smart-backend-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hire-smart-backend-network

  hire-smart-backend-redis:
    image: redis:7
    container_name: hire-smart-backend-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - hire-smart-backend-redis-data:/data
    networks:
      - hire-smart-backend-network

  hire-smart-backend-queue:
    image: hiresmart-backend-app:latest
    container_name: hire-smart-backend-queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./html/hiresmart-backend.rokanchowdhuryonick.com:/var/www/html
    depends_on:
      - hire-smart-backend-db
      - hire-smart-backend-redis
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=60
    networks:
      - hire-smart-backend-network
    environment:
      - DB_HOST=hire-smart-backend-db
      - DB_DATABASE=${DB_DATABASE:-hire_smart}
      - DB_USERNAME=${DB_USERNAME:-hire_smart_user}
      - DB_PASSWORD=${DB_PASSWORD:-hire_smart_password}
      - REDIS_HOST=hire-smart-backend-redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis

  hire-smart-backend-scheduler:
    image: hiresmart-backend-app:latest
    container_name: hire-smart-backend-scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./html/hiresmart-backend.rokanchowdhuryonick.com:/var/www/html
    depends_on:
      - hire-smart-backend-db
      - hire-smart-backend-redis
    command: php artisan schedule:work
    networks:
      - hire-smart-backend-network
    environment:
      - DB_HOST=hire-smart-backend-db
      - DB_DATABASE=${DB_DATABASE:-hire_smart}
      - DB_USERNAME=${DB_USERNAME:-hire_smart_user}
      - DB_PASSWORD=${DB_PASSWORD:-hire_smart_password}
      - REDIS_HOST=hire-smart-backend-redis
      - REDIS_PORT=6379

  hire-smart-backend-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hire-smart-backend-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-hello+pgadmin@rokanbd.cf}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
    ports:
      - "8081:80"
    depends_on:
      - hire-smart-backend-db
    networks:
      - hire-smart-backend-network
    volumes:
      - hire-smart-backend-pgadmin-data:/var/lib/pgadmin

volumes:
  hire-smart-backend-db-data:
    driver: local
  hire-smart-backend-redis-data:
    driver: local
  hire-smart-backend-pgadmin-data:
    driver: local

networks:
  hire-smart-backend-network:
    driver: bridge 